name: Run test when push to main

on:
  push:
    branches: [ "main" ]
    
jobs:
  run-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: khoanhuynh-evizi/RC360-WDIO 
          token: ${{ secrets.WDIO_ACCESS_TOKEN }}
          ref: demo
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
      - run: yarn install --frozen-lockfile
      - name: Run tests
        uses: mathiasvr/command-output@v1
        id: tests
        with:
          run: yarn test --suite="Specific Feature Test" --features="Failed, Passed" --reporter="Spec Reporter" 
      - name: Allure Reporter generator
        uses: simple-elf/allure-report-action@master
        if: always()
        id: allure-report
        with:
          allure_results: reports
          gh_pages: gh-pages
          allure_report: allure-report
          allure_history: allure-history
      - run: | 
          cat > .allure-report/specs-reporter.logs <<EOL
          ${{ steps.tests.outputs.stdout }}
          EOL
      - run: echo $(egrep '[0-9]+\sfailed,\s[0-9]+\stotal' .allure-report/specs-reporter.log) >> $GITHUB_ENV
      - name: Test Checker
        run: |
          if [ -z "${{ env.GITHUB_BASE_REF }}" ]; then
            exit 1
          fi
      - name: Deploy Report to Github Pages
        if: always()
        uses: peaceiris/actions-gh-pages@v3
        with:
          external_repository: khoanhuynh-evizi/dashboard-demo
          publish_dir: ./allure-report
          personal_token: ${{ secrets.WDIO_ACCESS_TOKEN }}
      
